name: linting, testing, building,
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    pipeline:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node_version: [20.x]

        steps:
            - uses: actions/checkout@v4

            - name: Starting Node.js ${{matrix.node-version}}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{matrix.node-version}}

            - name: Setup pnpm
              uses: pnpm/action-setup@v3
              with:
                  version: 8

            - name: Install modules
              run: pnpm install

            - name: Build production
              run: pnpm build:prod

            - name: Linting
              run: pnpm lint

            - name: Unit testing
              run: pnpm test:unit

            - name: Build storybook
              run: pnpm storybook:build

            - name: Screenshot testing
              run: pnpm loki --requireReference --reactUri file:./storybook-static
